### user/Param
http://localhost:8080/D20230928_spring_war/User/no-param?name=1&id=1&username=2
Content-Type: application/json

### user/Param-pojo
http://localhost:8080/D20230928_spring_war/User/param-pojo?id=1&name=12
Content-Type: application/json

### user/Param-pojo-body
http://localhost:8080/D20230928_spring_war/User/param-pojo-body
Content-Type: application/json

{
  "name" : "123",
  "id" : "1"
}


### user/date-time-format
GET http://localhost:8080/D20230928_spring_war/User/date-time-format?dateDay=1234-12-12
Content-Type: application/json